# site settings
title: Jingjing
subtitle: Liang
email: jliang2@nd.edu
description:  Data cruncher, Passionate explorer and much more .
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
city: South Bend
state: IN
zip_code: 46637
country: United States of America
phone: (574) 314-4849

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/JingjingLiang99
  LinkedIn: https://www.linkedin.com/in/jingjing-liang-2201361a3/


# build settings
markdown: kramdown
kramdown:
  parse_block_html: true
  
plugins:
  - jekyll-seo-tag
  - jekyll-feed

sass:
  style: compressed
  
instagram_user_id: 1019817961
instagram_client_id: 487609536578751
instagram_access_token: 4c148662572ca3509a654f08b2e6a229
  
include:
  - _menus
  - _posts

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
